### ISSUE TITLE
In production environment Doctrine cannot find proxy classes

### ISSUE THREAD

**Issue by petrparolek** [contributte/doctrine-orm#121]
Version:  0.10.0

### Bug Description
In production environment Doctrine cannot find proxy classes

### Steps To Reproduce

```
nettrine.orm:
  managers:
    default:
      connection: default
      mapping:
        App:
          directories: [%appDir%/Database]
          namespace: App/Database
```

### Expected Behavior

no error

### Possible Solution

```
diff --git a/src/DI/OrmExtension.php b/src/DI/OrmExtension.php
index f123a4b..60bae22 100644
--- a/src/DI/OrmExtension.php
+++ b/src/DI/OrmExtension.php
@@ -128,7 +128,7 @@ final class OrmExtension extends CompilerExtension
 							'namespace' => Expect::string()->required(),
 						]),
 						Expect::string()
-					)->required()->assert(fn ($input) => count($input) > 0, 'At least one mapping must be defined'),
+					),
 					'defaultCache' => (clone $expectService),
 					'queryCache' => (clone $expectService),
 					'resultCache' => (clone $expectService),
```
